package vista;

import java.awt.event.ActionListener;
import java.text.DecimalFormat;

/**
 *
 * @author Handry Serrano Fabela
 */
public class TemperaturaVista extends javax.swing.JPanel {

    /**
     * Creates new form VistaTemperatura
     */
    public TemperaturaVista() {
        initComponents();
    }
    
    public void addEventos(ActionListener oyente) {
        botonFahACel.addActionListener(oyente);
        botonCelAFah.addActionListener(oyente);
        botonCelAKel.addActionListener(oyente);
        botonKelACel.addActionListener(oyente);
    }
    
    public double getGradosTemperatura() {
        
        return Double.parseDouble(campoGrados.getText());
        
    }

    public void setGradosInicial(double temperatura) {
        
        etiquetaGradosInicial.setText(Double.toString(temperatura));
        
    }

    public void setEscalaInicial(String tipo) {
        
        etiquetaEscalaInicial.setText(tipo);
        
    }

    public void setEscalaFinal(String tipo) {
        
        etiquetaEscalaFinal.setText(tipo);
        
    }

    public void setGradosFinal(double resultado) {
        
        DecimalFormat formatoDecimal = new DecimalFormat("#.##");
        etiquetaGradosFinal.setText(formatoDecimal.format(resultado));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        panelNorteTitulo = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        panelNorteGrados = new javax.swing.JPanel();
        etiquetaGrados = new javax.swing.JLabel();
        campoGrados = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        panelCentroBotones = new javax.swing.JPanel();
        botonFahACel = new javax.swing.JButton();
        botonCelAFah = new javax.swing.JButton();
        botonCelAKel = new javax.swing.JButton();
        botonKelACel = new javax.swing.JButton();
        panelCentroConversiones = new javax.swing.JPanel();
        panelEscalaInicial = new javax.swing.JPanel();
        etiquetaGradosInicial = new javax.swing.JLabel();
        etiquetaLeyendaGrados = new javax.swing.JLabel();
        etiquetaEscalaInicial = new javax.swing.JLabel();
        panelIntermedio = new javax.swing.JPanel();
        etiquetaEquivale = new javax.swing.JLabel();
        panelEscalaFinal = new javax.swing.JPanel();
        etiquetaGradosFinal = new javax.swing.JLabel();
        etiquetaLeyendaGrados2 = new javax.swing.JLabel();
        etiquetaEscalaFinal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.GridLayout(2, 1));

        etiquetaTitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaTitulo.setText("CONVERSOR DE TEMPERATURA");
        panelNorteTitulo.add(etiquetaTitulo);

        panelNorte.add(panelNorteTitulo);

        panelNorteGrados.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        etiquetaGrados.setText("Grados: ");
        panelNorteGrados.add(etiquetaGrados);

        campoGrados.setColumns(6);
        panelNorteGrados.add(campoGrados);

        panelNorte.add(panelNorteGrados);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        panelCentroBotones.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelCentroBotones.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        botonFahACel.setText("°F a °C");
        panelCentroBotones.add(botonFahACel);

        botonCelAFah.setText("°C a °F ");
        panelCentroBotones.add(botonCelAFah);

        botonCelAKel.setText("°C a K");
        panelCentroBotones.add(botonCelAKel);

        botonKelACel.setText("K a °C");
        panelCentroBotones.add(botonKelACel);

        panelCentro.add(panelCentroBotones);

        panelCentroConversiones.setLayout(new java.awt.GridLayout(3, 1));

        etiquetaGradosInicial.setText("0.0");
        panelEscalaInicial.add(etiquetaGradosInicial);

        etiquetaLeyendaGrados.setText("grados");
        panelEscalaInicial.add(etiquetaLeyendaGrados);

        etiquetaEscalaInicial.setText("Celsius");
        panelEscalaInicial.add(etiquetaEscalaInicial);

        panelCentroConversiones.add(panelEscalaInicial);

        etiquetaEquivale.setText("equivale");
        panelIntermedio.add(etiquetaEquivale);

        panelCentroConversiones.add(panelIntermedio);

        etiquetaGradosFinal.setText("0.0");
        panelEscalaFinal.add(etiquetaGradosFinal);

        etiquetaLeyendaGrados2.setText("grados");
        panelEscalaFinal.add(etiquetaLeyendaGrados2);

        etiquetaEscalaFinal.setText("Kelvin");
        panelEscalaFinal.add(etiquetaEscalaFinal);

        panelCentroConversiones.add(panelEscalaFinal);

        panelCentro.add(panelCentroConversiones);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCelAFah;
    public javax.swing.JButton botonCelAKel;
    public javax.swing.JButton botonFahACel;
    public javax.swing.JButton botonKelACel;
    private javax.swing.JTextField campoGrados;
    private javax.swing.JLabel etiquetaEquivale;
    private javax.swing.JLabel etiquetaEscalaFinal;
    private javax.swing.JLabel etiquetaEscalaInicial;
    private javax.swing.JLabel etiquetaGrados;
    private javax.swing.JLabel etiquetaGradosFinal;
    private javax.swing.JLabel etiquetaGradosInicial;
    private javax.swing.JLabel etiquetaLeyendaGrados;
    private javax.swing.JLabel etiquetaLeyendaGrados2;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelCentroBotones;
    private javax.swing.JPanel panelCentroConversiones;
    private javax.swing.JPanel panelEscalaFinal;
    private javax.swing.JPanel panelEscalaInicial;
    private javax.swing.JPanel panelIntermedio;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelNorteGrados;
    private javax.swing.JPanel panelNorteTitulo;
    // End of variables declaration//GEN-END:variables
}
