/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Examen;

import javax.swing.JButton;

/**
 *
 * @author LENOVO
 */
public class VistaExamen extends javax.swing.JFrame {

    /**
     * Creates new form VistaExamen
     */
    public VistaExamen() {
        initComponents();
    }
    
    public void addEventos(ControlExamen oyente){
        this.aumentarLados.addActionListener(oyente);
        this.disminuirLados.addActionListener(oyente);
    }
    
    public JButton getAumentarLados(){
        return aumentarLados;
    }
    
    public JButton getDisminuirLados(){
        return aumentarLados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aumentarLados = new javax.swing.JButton();
        disminuirLados = new javax.swing.JButton();
        panelDibujo2 = new poligonoconeventos.PanelDibujo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aumentarLados.setText("Aumentar");
        jPanel1.add(aumentarLados);

        disminuirLados.setText("Disminuir");
        jPanel1.add(disminuirLados);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(panelDibujo2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aumentarLados;
    private javax.swing.JButton disminuirLados;
    private javax.swing.JPanel jPanel1;
    private poligonoconeventos.PanelDibujo panelDibujo2;
    // End of variables declaration//GEN-END:variables
}
