package examen;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Serrano Fabela Handry
 */
public class PanelExamen extends javax.swing.JPanel {

    /**
     * Creates new form PanelExamen
     */
    public PanelExamen() {
        initComponents();
    }

    public void addEventos(OyenteExamen oyente) {
        this.campoCantidad.addActionListener(oyente);
    }

    public JLabel[] getResultados() {
        return new JLabel[]{resultadoM1, resultadoM2, resultadoM5, resultadoM10, resultadoM20,
                            resultadoB50, resultadoB100, resultadoB200, resultadoB500};
    }

    public int getCampoCantidad() {
        return Integer.parseInt(campoCantidad.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JLabel();
        campoCantidad = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        etiquetaDenominacion = new javax.swing.JLabel();
        etiquetaCantidad = new javax.swing.JLabel();
        etiquetaDenominacion2 = new javax.swing.JLabel();
        etiquetaCantidad2 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JLabel();
        resultadoB500 = new javax.swing.JLabel();
        txtC2 = new javax.swing.JLabel();
        resultadoM10 = new javax.swing.JLabel();
        txtC3 = new javax.swing.JLabel();
        resultadoB200 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        resultadoM5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        resultadoB100 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        resultadoM2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        resultadoB50 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        resultadoM1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        resultadoM20 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        txtCantidad.setText("Cantidad:");
        panelNorte.add(txtCantidad);

        campoCantidad.setColumns(9);
        panelNorte.add(campoCantidad);

        add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelCentro.setLayout(new java.awt.GridLayout(6, 4));

        etiquetaDenominacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDenominacion.setText("Denominacion");
        panelCentro.add(etiquetaDenominacion);

        etiquetaCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCantidad.setText("Cantidad");
        panelCentro.add(etiquetaCantidad);

        etiquetaDenominacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDenominacion2.setText("Denominacion");
        panelCentro.add(etiquetaDenominacion2);

        etiquetaCantidad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCantidad2.setText("Cantidad");
        panelCentro.add(etiquetaCantidad2);

        txtCantidad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad1.setText("500");
        panelCentro.add(txtCantidad1);

        resultadoB500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoB500);

        txtC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtC2.setText("10");
        panelCentro.add(txtC2);

        resultadoM10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoM10);

        txtC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtC3.setText("200");
        panelCentro.add(txtC3);

        resultadoB200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoB200);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("5");
        panelCentro.add(jLabel11);

        resultadoM5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoM5);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("100");
        panelCentro.add(jLabel13);

        resultadoB100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoB100);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("2");
        panelCentro.add(jLabel15);

        resultadoM2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoM2);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("50");
        panelCentro.add(jLabel17);

        resultadoB50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoB50);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("1");
        panelCentro.add(jLabel19);

        resultadoM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoM1);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("20");
        panelCentro.add(jLabel21);

        resultadoM20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCentro.add(resultadoM20);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCantidad;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaCantidad2;
    private javax.swing.JLabel etiquetaDenominacion;
    private javax.swing.JLabel etiquetaDenominacion2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JLabel resultadoB100;
    private javax.swing.JLabel resultadoB200;
    private javax.swing.JLabel resultadoB50;
    private javax.swing.JLabel resultadoB500;
    private javax.swing.JLabel resultadoM1;
    private javax.swing.JLabel resultadoM10;
    private javax.swing.JLabel resultadoM2;
    private javax.swing.JLabel resultadoM20;
    private javax.swing.JLabel resultadoM5;
    private javax.swing.JLabel txtC2;
    private javax.swing.JLabel txtC3;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtCantidad1;
    // End of variables declaration//GEN-END:variables
}
