/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poligonoconeventos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class VentanaPoligono extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPoligono
     */
    public VentanaPoligono() {
        initComponents();
        this.campoLados.addActionListener(new OyenteVentana());
                
    }

    private class OyenteVentana implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            
            String texto = campoLados.getText();
            try{
                panelCentro.setLados(Integer.parseInt(texto));
            } catch(NumberFormatException ex){
                
                JOptionPane.showMessageDialog(panelCentro, "Captura un valor numerico entero", "Error de captura", JOptionPane.ERROR_MESSAGE);
                panelCentro.setLados(0);
                campoLados.setText("");
                
            }
            panelCentro.repaint();   
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        etiquetaLados = new javax.swing.JLabel();
        campoLados = new javax.swing.JTextField();
        panelCentro = new poligonoconeventos.PanelDibujo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaLados.setText("Número De Lados: ");
        panelNorte.add(etiquetaLados);

        campoLados.setColumns(10);
        panelNorte.add(campoLados);

        getContentPane().add(panelNorte, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoLados;
    private javax.swing.JLabel etiquetaLados;
    private poligonoconeventos.PanelDibujo panelCentro;
    private javax.swing.JPanel panelNorte;
    // End of variables declaration//GEN-END:variables
}
