package eventoboton;

/**
 *
 * @author Handry Serrano Fabela Handry
 */
public class PanelEventoBoton extends javax.swing.JPanel {

    /**
     * Creates new form PanelEventoBoton
     */
    public PanelEventoBoton() {
        initComponents();
    }
    
    public void addEventos(OyenteEventoBoton oyente){
    
        botonAzul.addActionListener(oyente);
        botonVerde.addActionListener(oyente);
        botonRojo.addActionListener(oyente);
        botonAmarillo.addActionListener(oyente);
        botonAzul.setName("azul");
        botonVerde.setName("verde");
        botonRojo.setName("rojo");
        botonAmarillo.setName("amarillo");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAzul = new javax.swing.JButton();
        botonVerde = new javax.swing.JButton();
        botonRojo = new javax.swing.JButton();
        botonAmarillo = new javax.swing.JButton();

        botonAzul.setText("Cambiar fondo a Azul");
        botonAzul.setName("azul"); // NOI18N
        add(botonAzul);

        botonVerde.setText("Cambiar fondo a Verde");
        add(botonVerde);

        botonRojo.setText("Cambiar fondo a Rojo");
        add(botonRojo);

        botonAmarillo.setText("Cambiar fondo a Amarillo");
        add(botonAmarillo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAmarillo;
    private javax.swing.JButton botonAzul;
    private javax.swing.JButton botonRojo;
    private javax.swing.JButton botonVerde;
    // End of variables declaration//GEN-END:variables
}
