package vista;

/**
 *
 * @author Handry Serrano Fabela
 */
public class ConteoPalabrasVista extends javax.swing.JDialog {

  public ConteoPalabrasVista(java.awt.Frame parent, boolean modal, String[] lineas) {
    super(parent, modal);
    initComponents();
    actualizarEtiquetas(lineas);
  }

  public void actualizarEtiquetas(String[] lineas) {
    int contador = 0;
    for (String linea : lineas) {
      if (!"".equals(linea)) {
        contador += linea.split("\\s+").length;
      }
    }
    this.etiquetaPalabras.setText("Las Palabras Totales En El Texto Son: " + contador);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaPalabras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etiquetaPalabras.setText("Las Palabras Totales En El Texto Son: ");
        getContentPane().add(etiquetaPalabras, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaPalabras;
    // End of variables declaration//GEN-END:variables
}
