package vista;

import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JTextArea;

/**
 *
 * @author Handry Serrano Fabela
 */
public class VentanaEditorVista extends javax.swing.JFrame {
  
  private ArrayList<String> lineas;
  private File archivo;

  /**
   * Creates new form VentanaEditorArchivo
   */
  public VentanaEditorVista() {
    initComponents();
  }

  public void addEventos(ActionListener e) {
    this.opcionAbrir.addActionListener(e);
    this.opcionGuardar.addActionListener(e);
    this.opcionSalir.addActionListener(e);
    this.opcionCopiar.addActionListener(e);
    this.opcionCortar.addActionListener(e);
    this.opcionPegar.addActionListener(e);
    this.opcionMayusculas.addActionListener(e);
    this.opcionMinusculas.addActionListener(e);
    this.opcionContarPalabras.addActionListener(e);

    this.opcionAbrir.setName("abrir");
    this.opcionGuardar.setName("guardar");
    this.opcionSalir.setName("salir");
    this.opcionCopiar.setName("copiar");
    this.opcionCortar.setName("cortar");
    this.opcionPegar.setName("pegar");
    this.opcionMayusculas.setName("mayusculas");
    this.opcionMinusculas.setName("minusculas");
    this.opcionContarPalabras.setName("contar");
  }
    public ArrayList<String> getLineas() {
    return lineas;
  }

  public File getArchivo() {
    return archivo;
  }

  public JTextArea getAreaTexto() {
    return areaTexto;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionAbrir = new javax.swing.JMenuItem();
        opcionGuardar = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        opcionCopiar = new javax.swing.JMenuItem();
        opcionCortar = new javax.swing.JMenuItem();
        opcionPegar = new javax.swing.JMenuItem();
        menuFuente = new javax.swing.JMenu();
        opcionMayusculas = new javax.swing.JMenuItem();
        opcionMinusculas = new javax.swing.JMenuItem();
        opcionContarPalabras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        opcionAbrir.setText("Abrir Archivo");
        menuArchivo.add(opcionAbrir);

        opcionGuardar.setText("Guardar Archivo");
        menuArchivo.add(opcionGuardar);
        menuArchivo.add(separador);

        opcionSalir.setText("Salir Del Programa");
        menuArchivo.add(opcionSalir);

        barraMenu.add(menuArchivo);

        menuEditar.setText("Editar");

        opcionCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcionCopiar.setText("Copiar");
        menuEditar.add(opcionCopiar);

        opcionCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcionCortar.setText("Cortar");
        menuEditar.add(opcionCortar);

        opcionPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcionPegar.setText("Pegar");
        menuEditar.add(opcionPegar);

        barraMenu.add(menuEditar);

        menuFuente.setText("Fuentes");

        opcionMayusculas.setText("Cambiar Mayusculas");
        menuFuente.add(opcionMayusculas);

        opcionMinusculas.setText("Cambiar Minusculas");
        menuFuente.add(opcionMinusculas);

        opcionContarPalabras.setText("Conteo Palabras");
        menuFuente.add(opcionContarPalabras);

        barraMenu.add(menuFuente);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuFuente;
    private javax.swing.JMenuItem opcionAbrir;
    private javax.swing.JMenuItem opcionContarPalabras;
    private javax.swing.JMenuItem opcionCopiar;
    private javax.swing.JMenuItem opcionCortar;
    private javax.swing.JMenuItem opcionGuardar;
    private javax.swing.JMenuItem opcionMayusculas;
    private javax.swing.JMenuItem opcionMinusculas;
    private javax.swing.JMenuItem opcionPegar;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
