package tarea;

/**
 *
 * @author Handry Serrano Fabela
 */
public class VentanaComponentes extends javax.swing.JPanel {

    /**
     * Creates new form VentanaComponentes
     */
    public VentanaComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printer = new javax.swing.JLabel();
        panelEste = new javax.swing.JPanel();
        opcionOk = new javax.swing.JButton();
        opcionCancel = new javax.swing.JButton();
        opcionSetup = new javax.swing.JButton();
        opcionHelp = new javax.swing.JButton();
        panelSur = new javax.swing.JPanel();
        print = new javax.swing.JLabel();
        comboHigh = new javax.swing.JComboBox<>();
        checkPrint = new javax.swing.JCheckBox();
        panelCentro = new javax.swing.JPanel();
        opcionImage = new javax.swing.JCheckBox();
        opcionSeleccion = new javax.swing.JRadioButton();
        opcionText = new javax.swing.JCheckBox();
        opcionAll = new javax.swing.JRadioButton();
        opcionCode = new javax.swing.JCheckBox();
        opcionApplet = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 15));
        setLayout(new java.awt.BorderLayout());

        printer.setText("Printer: MyPrinter");
        add(printer, java.awt.BorderLayout.PAGE_START);

        panelEste.setLayout(new java.awt.GridLayout(4, 1));

        opcionOk.setText("Ok");
        panelEste.add(opcionOk);

        opcionCancel.setText("Cancel");
        panelEste.add(opcionCancel);

        opcionSetup.setText("Setup");
        panelEste.add(opcionSetup);

        opcionHelp.setText("Help");
        panelEste.add(opcionHelp);

        add(panelEste, java.awt.BorderLayout.LINE_END);

        panelSur.setLayout(new java.awt.GridLayout(1, 0));

        print.setText("Print Quality:");
        panelSur.add(print);

        comboHigh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High" }));
        panelSur.add(comboHigh);

        checkPrint.setText("Print to File");
        panelSur.add(checkPrint);

        add(panelSur, java.awt.BorderLayout.PAGE_END);

        panelCentro.setLayout(new java.awt.GridLayout(3, 2));

        opcionImage.setText("Image");
        panelCentro.add(opcionImage);

        opcionSeleccion.setText("Seleccion");
        panelCentro.add(opcionSeleccion);

        opcionText.setText("Text");
        panelCentro.add(opcionText);

        opcionAll.setText("All");
        panelCentro.add(opcionAll);

        opcionCode.setText("Code");
        panelCentro.add(opcionCode);

        opcionApplet.setText("Applet");
        panelCentro.add(opcionApplet);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkPrint;
    private javax.swing.JComboBox<String> comboHigh;
    private javax.swing.JRadioButton opcionAll;
    private javax.swing.JRadioButton opcionApplet;
    private javax.swing.JButton opcionCancel;
    private javax.swing.JCheckBox opcionCode;
    private javax.swing.JButton opcionHelp;
    private javax.swing.JCheckBox opcionImage;
    private javax.swing.JButton opcionOk;
    private javax.swing.JRadioButton opcionSeleccion;
    private javax.swing.JButton opcionSetup;
    private javax.swing.JCheckBox opcionText;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelEste;
    private javax.swing.JPanel panelSur;
    private javax.swing.JLabel print;
    private javax.swing.JLabel printer;
    // End of variables declaration//GEN-END:variables
}
