package examencuadricula;

/**
 *
 * @author Barradas Cortés Abraham
 */
public class VentanaCuadricula extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCuadricula
     */
    public VentanaCuadricula() {
        initComponents();
        modeloCuadricula1.repaint();
    }

    public void addEventos(OyenteCuadricula oyente) {
        this.opcionAbrir.addActionListener(oyente);
        this.opcionSalir.addActionListener(oyente);

        this.opcionAbrir.setName("abrir");
        this.opcionSalir.setName("salir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeloCuadricula1 = new examencuadricula.ModeloCuadricula();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionAbrir = new javax.swing.JMenuItem();
        separadorArchivo = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Malla");
        getContentPane().add(modeloCuadricula1, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        opcionAbrir.setText("Abrir archivo");
        opcionAbrir.setName("abrir"); // NOI18N
        menuArchivo.add(opcionAbrir);
        menuArchivo.add(separadorArchivo);

        opcionSalir.setText("Salir del programa");
        opcionSalir.setName("salir"); // NOI18N
        menuArchivo.add(opcionSalir);

        barraMenu.add(menuArchivo);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuArchivo;
    private examencuadricula.ModeloCuadricula modeloCuadricula1;
    private javax.swing.JMenuItem opcionAbrir;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JPopupMenu.Separator separadorArchivo;
    // End of variables declaration//GEN-END:variables
}
