package examen;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class VistaExamen extends javax.swing.JPanel {

    /**
     * Creates new form VistaExamen
     */
    public VistaExamen() {
        initComponents();
    }

    public void addEventos(OyenteExamen oyente) {
        this.campoTexto.addActionListener(oyente);
        this.op1.addActionListener(oyente);
        this.op2.addActionListener(oyente);
        this.op3.addActionListener(oyente);
        this.op4.addActionListener(oyente);
        this.op5.addActionListener(oyente);
        this.op6.addActionListener(oyente);
        this.op7.addActionListener(oyente);
        this.op8.addActionListener(oyente);
        this.op9.addActionListener(oyente);
        this.campoTexto.setName("campo");
        this.op1.setName("numero1");
        this.op2.setName("numero2");
        this.op3.setName("numero3");
        this.op4.setName("numero4");
        this.op5.setName("numero5");
        this.op6.setName("numero6");
        this.op7.setName("numero7");
        this.op8.setName("numero8");
        this.op9.setName("numero9");
    }

    public JTextField getCampoTexto() {
        return campoTexto;
    }

    public void setCampoTexto(JTextField campoTexto) {
        this.campoTexto = campoTexto;
    }
    
    
    
    public void boton1() {
    
        int num = 1;
        campoTexto.setText(Integer.toString(num));
    
    }
    
    public void boton2() {
    
        int num = 2;
        campoTexto.setText(Integer.toString(num));
    
    }
    
    public void boton3() {
    
        int num = 3;
        campoTexto.setText(Integer.toString(num));
    
    }
    
    public void boton4() {
    
        int num = 4;
        campoTexto.setText(Integer.toString(num));
    
    }
    
    public void boton5() {
    
        int num = 5;
        campoTexto.setText(Integer.toString(num));
    
    }
    
    public void boton6() {
    
        int num = 6;
        campoTexto.setText(Integer.toString(num));
    
    }
    public void boton7() {
    
        int num = 7;
        campoTexto.setText(Integer.toString(num));
    
    }
    public void boton8() {
    
        int num = 8;
        campoTexto.setText(Integer.toString(num));
    
    }
    
    public void boton9() {
    
        int num = 9;
        campoTexto.setText(Integer.toString(num));
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        campoTexto = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        op1 = new javax.swing.JButton();
        op4 = new javax.swing.JButton();
        op7 = new javax.swing.JButton();
        op2 = new javax.swing.JButton();
        op5 = new javax.swing.JButton();
        op8 = new javax.swing.JButton();
        op3 = new javax.swing.JButton();
        op6 = new javax.swing.JButton();
        op9 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.GridLayout(1, 1));
        panelNorte.add(campoTexto);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setLayout(new java.awt.GridLayout(3, 3));

        op1.setText("1");
        panelCentro.add(op1);

        op4.setText("4");
        panelCentro.add(op4);

        op7.setText("7");
        panelCentro.add(op7);

        op2.setText("2");
        panelCentro.add(op2);

        op5.setText("5");
        panelCentro.add(op5);

        op8.setText("8");
        panelCentro.add(op8);

        op3.setText("3");
        panelCentro.add(op3);

        op6.setText("6");
        panelCentro.add(op6);

        op9.setText("9");
        panelCentro.add(op9);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTexto;
    private javax.swing.JButton op1;
    private javax.swing.JButton op2;
    private javax.swing.JButton op3;
    private javax.swing.JButton op4;
    private javax.swing.JButton op5;
    private javax.swing.JButton op6;
    private javax.swing.JButton op7;
    private javax.swing.JButton op8;
    private javax.swing.JButton op9;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    // End of variables declaration//GEN-END:variables
}
