/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package menuconeventos;

/**
 *
 * @author LENOVO
 */
public class DialogoAcercaDe extends javax.swing.JDialog {

    /**
     * Creates new form DialogoAcercaDe
     */
    public DialogoAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSur = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        panelCentro = new javax.swing.JScrollPane();
        panelEditor = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca Del Programa");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        panelSur.add(botonAceptar);

        getContentPane().add(panelSur, java.awt.BorderLayout.SOUTH);

        panelEditor.setEditable(false);
        try {
            panelEditor.setPage(getClass().getResource("/html/AcercaDe.html"));
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        panelCentro.setViewportView(panelEditor);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JScrollPane panelCentro;
    private javax.swing.JEditorPane panelEditor;
    private javax.swing.JPanel panelSur;
    // End of variables declaration//GEN-END:variables
}
