/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuconeventos;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import util.Archivo;

/**
 *
 * @author LENOVO
 */
public class VentanaConEventos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConEventos
     */
    public VentanaConEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new poligonoconeventos.PanelDibujo();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionAbrir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        opcionAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventana Con Eventos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        opcionAbrir.setText("Abrir Archivo");
        opcionAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivo(evt);
            }
        });
        menuArchivo.add(opcionAbrir);
        menuArchivo.add(jSeparator1);

        opcionSalir.setText("Salir Del Programa");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(opcionSalir);

        barraMenu.add(menuArchivo);

        menuAyuda.setText("Ayuda");

        opcionAcercaDe.setText("Acerca De");
        opcionAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(opcionAcercaDe);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        salirDelPrograma();
    }//GEN-LAST:event_formWindowClosing

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        salirDelPrograma();
    }//GEN-LAST:event_opcionSalirActionPerformed

    private void abrirArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivo
       JFileChooser selector = new JFileChooser();
       FileFilter filtro = new FileNameExtensionFilter("Archivos de poligonos", "lados");
       selector.setFileFilter(filtro);
       int opcion = selector.showOpenDialog(this);
       if(opcion == JFileChooser.APPROVE_OPTION) {
       
           //File archivo = selector.getSelectedFile();
           ArrayList<String> lineas = Archivo.leerArchivo(selector.getSelectedFile());
           try{
           
               //int ladosDelArchivo = Integer.parseInt(lineas.get(0));
               panelCentro.setLados(Integer.parseInt(lineas.get(0)));
               
           }catch(NumberFormatException nfe) {
           
               panelCentro.setLados(0);
               
           }
       
           this.repaint();
           
       }
    }//GEN-LAST:event_abrirArchivo

    private void opcionAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAcercaDeActionPerformed
        DialogoAcercaDe dialogo = new DialogoAcercaDe(this,true);
        dialogo.setSize(500,400);
        int dX = this.getX()+this.getWidth()/2-dialogo.getWidth()/2;
        int dY = this.getY()+100;
        dialogo.setLocation(dX,dY);
        dialogo.setVisible(true);
    }//GEN-LAST:event_opcionAcercaDeActionPerformed

    public void salirDelPrograma(){
    
        int  opcion = JOptionPane.showConfirmDialog(this, "¿Desea Salir Del Programa?","Confirmacion de salida", JOptionPane.OK_CANCEL_OPTION);
        if(opcion == JOptionPane.OK_OPTION) {
        
            System.exit(0);
        
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem opcionAbrir;
    private javax.swing.JMenuItem opcionAcercaDe;
    private javax.swing.JMenuItem opcionSalir;
    private poligonoconeventos.PanelDibujo panelCentro;
    // End of variables declaration//GEN-END:variables
}
