/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesconherencia;

/**
 *
 * @author LENOVO
 */
public class PanelHijo extends PanelPadre {

    /**
     * Creates new form PanelHijo
     */
    public PanelHijo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonHijo = new javax.swing.JButton();

        botonHijo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonHijo.setText("MÉXICO");
        botonHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHijoActionPerformed(evt);
            }
        });
        add(botonHijo);
    }// </editor-fold>//GEN-END:initComponents

    private void botonHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonHijoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonHijo;
    // End of variables declaration//GEN-END:variables
}
