package tarea;

/**
 *
 * @author Handry Serrano Fabela
 */
public class VentanaComponentes extends javax.swing.JPanel {

    /**
     * Creates new form VentanaComponentes
     */
    public VentanaComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        campoTexto = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        op7 = new javax.swing.JButton();
        op8 = new javax.swing.JButton();
        op9 = new javax.swing.JButton();
        opDividir = new javax.swing.JButton();
        op4 = new javax.swing.JButton();
        op5 = new javax.swing.JButton();
        op6 = new javax.swing.JButton();
        opMultiplicar = new javax.swing.JButton();
        op1 = new javax.swing.JButton();
        op2 = new javax.swing.JButton();
        op3 = new javax.swing.JButton();
        opRestar = new javax.swing.JButton();
        op0 = new javax.swing.JButton();
        opPunto = new javax.swing.JButton();
        opIgual = new javax.swing.JButton();
        opSumar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.GridLayout(1, 1));
        panelNorte.add(campoTexto);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setLayout(new java.awt.GridLayout(4, 4));

        op7.setText("7");
        panelCentro.add(op7);

        op8.setText("8");
        panelCentro.add(op8);

        op9.setText("9");
        panelCentro.add(op9);

        opDividir.setText("/");
        panelCentro.add(opDividir);

        op4.setText("4");
        panelCentro.add(op4);

        op5.setText("5");
        panelCentro.add(op5);

        op6.setText("6");
        panelCentro.add(op6);

        opMultiplicar.setText("*");
        panelCentro.add(opMultiplicar);

        op1.setText("1");
        panelCentro.add(op1);

        op2.setText("2");
        panelCentro.add(op2);

        op3.setText("3");
        panelCentro.add(op3);

        opRestar.setText("-");
        panelCentro.add(opRestar);

        op0.setText("0");
        panelCentro.add(op0);

        opPunto.setText(".");
        panelCentro.add(opPunto);

        opIgual.setText("=");
        panelCentro.add(opIgual);

        opSumar.setText("+");
        panelCentro.add(opSumar);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTexto;
    private javax.swing.JButton op0;
    private javax.swing.JButton op1;
    private javax.swing.JButton op2;
    private javax.swing.JButton op3;
    private javax.swing.JButton op4;
    private javax.swing.JButton op5;
    private javax.swing.JButton op6;
    private javax.swing.JButton op7;
    private javax.swing.JButton op8;
    private javax.swing.JButton op9;
    private javax.swing.JButton opDividir;
    private javax.swing.JButton opIgual;
    private javax.swing.JButton opMultiplicar;
    private javax.swing.JButton opPunto;
    private javax.swing.JButton opRestar;
    private javax.swing.JButton opSumar;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    // End of variables declaration//GEN-END:variables
}
