package tarea;

/**
 *
 * @author Handry Serrano Fabela
 */
public class VentanaComponentes extends javax.swing.JPanel {

    /**
     * Creates new form VentanaComponentes
     */
    public VentanaComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        panelNorte = new javax.swing.JPanel();
        opcionOk = new javax.swing.JButton();
        opcionCancel = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();
        opcionBackground = new javax.swing.JCheckBox();
        opcionForeground = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED" }));
        add(jComboBox1, java.awt.BorderLayout.PAGE_START);

        opcionOk.setText("Ok");
        panelNorte.add(opcionOk);

        opcionCancel.setText("Cancel");
        panelNorte.add(opcionCancel);

        add(panelNorte, java.awt.BorderLayout.PAGE_END);

        opcionBackground.setText("Background");
        panelCentro.add(opcionBackground);

        opcionForeground.setText("Foreground");
        panelCentro.add(opcionForeground);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JCheckBox opcionBackground;
    private javax.swing.JButton opcionCancel;
    private javax.swing.JCheckBox opcionForeground;
    private javax.swing.JButton opcionOk;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    // End of variables declaration//GEN-END:variables
}
