/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package editor;

import java.io.File;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.Archivo;

/**
 *
 * @author Handry Serrano Fabela
 */
public class PanelEditor extends javax.swing.JPanel {

    /**
     * Creates new form PanelEditor
     */
    public PanelEditor() {
        initComponents();

        abrirArchivo();
    }

    public void abrirArchivo() {

        //Abrir el archivo de texto
        String archivo = "/archivos/HimnoITV 1.txt";
        ArrayList<String> contenido = Archivo.leerArchivo(getClass().getResourceAsStream(archivo));
        for (String linea : contenido) {

            areaEditor.append(linea + "\n");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JScrollPane();
        areaEditor = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        panelCentro.setBorder(null);
        panelCentro.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        panelCentro.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        areaEditor.setColumns(20);
        areaEditor.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        areaEditor.setRows(5);
        areaEditor.setBorder(null);
        panelCentro.setViewportView(areaEditor);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaEditor;
    private javax.swing.JScrollPane panelCentro;
    // End of variables declaration//GEN-END:variables
}
